spring.application.name=APIGATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8067/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webmvc.routes[1].id=restaurant-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://RESTAURANTSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/restaurants/**
spring.cloud.gateway.server.webmvc.routes[2].id=order-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ORDERSERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/orders/**